import type { Metadata } from "next";
import { Inter, JetBrains_Mono, Source_Serif_4 } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { SiteChrome } from "@/components/layout/SiteChrome";
import "./globals.css";

// Sohne substitute — body, UI, navigation sans
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-geist",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  display: "swap",
  weight: ["400", "500", "600"],
});

// Signifier substitute — display / headline serif, weight 400 at every scale
const sourceSerif = Source_Serif_4({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  style: ["normal", "italic"],
  variable: "--font-kanit",
  display: "swap",
});

const siteUrl = "https://dheerajkashyap.com";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default:
      "Dheeraj Kashyap | Microsoft Certified BI & Analytics Engineer — Fabric, Power BI, Snowflake, Databricks",
    template: "%s | Dheeraj Kashyap",
  },
  description:
    "Dheeraj Kashyap — Microsoft Certified BI & Analytics Engineer at Amplify Analytix. 13× certified, 7+ years designing enterprise Lakehouse platforms, Power BI semantic models, and analytics pipelines on Microsoft Fabric, Databricks, and Snowflake across 15 countries.",
  keywords: [
    "Microsoft Certified BI Engineer",
    "BI & Analytics Engineer",
    "Analytics Engineer",
    "Microsoft Fabric",
    "Fabric Analytics Engineer",
    "DP-600",
    "Power BI Developer",
    "Power BI Semantic Model",
    "Databricks",
    "Snowflake",
    "Data Engineer",
    "Lakehouse Architecture",
    "Business Intelligence",
    "Analytics Engineering",
    "Dheeraj Kashyap",
    "dbt",
    "PySpark",
    "Delta Lake",
    "SQLMesh",
    "Direct Lake",
    "OneLake",
  ],
  authors: [{ name: "Dheeraj Kashyap", url: siteUrl }],
  creator: "Dheeraj Kashyap",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteUrl,
    siteName: "Dheeraj Kashyap",
    title: "Dheeraj Kashyap | BI & Analytics Engineer",
    description:
      "BI & Analytics Engineer at Amplify Analytix · 13× certified · Microsoft Fabric, Databricks, Snowflake, Power BI.",
    // Social image is generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Dheeraj Kashyap | BI & Analytics Engineer",
    description:
      "BI & Analytics Engineer at Amplify Analytix — Microsoft Fabric, Databricks, Snowflake, Power BI.",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: { canonical: siteUrl },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Dheeraj Kashyap",
  jobTitle: "BI & Analytics Engineer",
  worksFor: { "@type": "Organization", name: "Amplify Analytix" },
  description:
    "Business Intelligence & Analytics Engineer at Amplify Analytix — designing Lakehouse platforms, CI/CD data environments, and executive reporting with Microsoft Fabric, Databricks, Snowflake, and Power BI.",
  url: siteUrl,
  email: "kash.dheeraj.yap@gmail.com",
  address: {
    "@type": "PostalAddress",
    addressLocality: "Bengaluru",
    addressCountry: "IN",
  },
  sameAs: [
    "https://linkedin.com/in/kashyap-dheeraj",
    "https://github.com/dheekash",
  ],
  knowsAbout: [
    "Microsoft Fabric",
    "Databricks",
    "Snowflake",
    "Power BI",
    "Lakehouse Architecture",
    "Data Engineering",
    "Analytics Engineering",
    "Business Intelligence",
    "dbt",
    "PySpark",
    "Python",
    "SQL",
  ],
  alumniOf: [
    { "@type": "CollegeOrUniversity", name: "Deakin University" },
    { "@type": "CollegeOrUniversity", name: "The University of Texas at Austin" },
    { "@type": "CollegeOrUniversity", name: "Great Lakes Institute of Management" },
    { "@type": "CollegeOrUniversity", name: "REVA University" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Apply persisted theme before paint — light is the default */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              "(function(){try{if(localStorage.getItem('theme')==='light'){document.documentElement.classList.add('light')}}catch(e){}})()",
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className={`${inter.variable} ${jetbrainsMono.variable} ${sourceSerif.variable} font-sans antialiased`}>
        <ThemeProvider>
          <TooltipProvider>
            <SiteChrome>{children}</SiteChrome>
          </TooltipProvider>
        </ThemeProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
